# Generated by Django 4.2.1 on 2024-11-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='auto',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='auto',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AddIndex(
            model_name='auto',
            index=models.Index(fields=['-time_create'], name='auto_auto_time_cr_d40b62_idx'),
        ),
    ]
