# Generated by Django 4.2.1 on 2024-11-24 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_alter_auto_is_published_alter_auto_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='sed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auto.category'),
        ),
    ]
