# Generated by Django 5.1.3 on 2024-11-25 11:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_owner_auto_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='auto',
            options={'verbose_name': 'Автомобильный журнал', 'verbose_name_plural': 'Автомобильный журнал'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveIndex(
            model_name='auto',
            name='auto_auto_time_cr_d40b62_idx',
        ),
        migrations.AlterField(
            model_name='auto',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='auto.owner', verbose_name='Хозяин'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='sed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='auto.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='auto',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='auto.tagpost', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категория'),
        ),
    ]
